stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t my-backend backend/
    - docker build -t my-frontend frontend/

unit-test-job:
  stage: test
  script:
    - docker build -t my-backend backend/
    - docker run --rm my-backend python manage.py test -s -v

deploy-job:
  stage: deploy
  script:
    - apk add --no-cache py3-pip
    - pip install docker-compose
    - docker compose up -d