image: docker:24.0.2

services:
  - docker:24-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t my-backend backend/
    - docker build -t my-frontend frontend/

unit-test-job:
  stage: test
  script:
    - docker build -t my-backend backend/
    - docker run --rm my-backend python manage.py test -v 2

deploy-job:
  stage: deploy
  script:
    - docker compose up -d