stages:
  - build
  - test
  - deploy

variables:
  # Tell jobs to use rootless Docker (no socket needed)
  DOCKER_HOST: "unix:///run/user/$UID/docker.sock"

build-job:
  stage: build
  script:
    - echo "Building backend..."
    - docker build -t my-backend backend/
    - echo "Building frontend..."
    - docker build -t my-frontend frontend/

unit-test-job:
  stage: test
  script:
    - docker run --rm my-backend python3 manage.py test -v 2

deploy-job:
  stage: deploy
  script:
    - docker compose up -d